# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90687c55c00b31c5b572b116c788fea967e982d2e19b846d6f893fd6837082f46c182aa4adb1f2f8468e24b186a1be0c30358b5f112619eb111cc4132f77c7f5

test:
  secret_key_base: ffaef1a747b6aa9c2266b64ea6b7ee8621a0ed232b3080f62600c610d1f628e7d24906a60cdc2724436518c0a67421957fab0fa3333d68bb2d2b2e3910f3d290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
